\ProvidesClass{jmstatement}
\LoadClass[11pt,letterpaper]{article} % Font size and paper type

%--------------------------------------------------%
%                    packages                      %
%--------------------------------------------------%

% Document Formatting
\usepackage[margin=1.2in]{geometry}
% \usepackage{parskip}
\usepackage{fancyhdr}
\setlength{\headheight}{15pt}
\usepackage{xcolor}
\usepackage{bold-extra}
\usepackage{natbib}

% References and Citations
\usepackage{url}
\usepackage{hyperref}
\definecolor{dkgreen}{rgb}{0,0.6,0}
\definecolor{ucmaroon}{rgb}{0.50,0,0}
\hypersetup{
    pdfauthor={},
    colorlinks=true,   % false: boxed links; true: colored links
    citecolor=dkgreen,
    linkcolor=magenta,
    urlcolor=magenta   % color of external links
}