* advice from UChicago GRAD

A [[https://exqcbqgksyx.exactdn.com/wp-content/uploads/2022/07/HanlonTeaching-Statements-Remediated.pdf][teaching statement]] is a 1-2 page personal reflection on your pedagogy. It demonstrates that you've thought deeply about the practice of teaching in your discipline, and it shows that you can apply what you've learned to successfully teach a range of students in various settings. The statement is structured as an argument with specific examples that illustrate your approach and its impact on student learning. For further advice on writing an effective teaching statement, consult an advisor at the [[http://teaching.uchicago.edu/][Chicago Center for Teaching and Learning]].

- [ ] Goals :: Describe what you believe is an essential skill, concept, or disposition in your discipline and how you teach or plan to teach that skill, concept, or disposition to students.
- [ ] Values :: Think of a time when you experienced “good teaching.” Describe the context, the teacher(s), their teaching methods, and what you learned from them.
- [ ] Inclusion :: How do you create an inclusive classroom climate? What do you do, specifically, to create an inclusive educational experience for all students in your class?
- [ ] Methods :: Describe your most successful teaching or mentoring experience, including what you did, what the student(s) learned, and why you felt it was successful or how you knew it was successful.
- [ ] Assessment :: What kinds of work do you assign students? Describe an interesting/effective/unique assignment. Why did you assign it, i.e. what did you want students to learn through it or to demonstrate? How did you know it was successful?